name = "wenya-lexicon-ai"
compatibility_date = "2024-04-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "wenya_db"
database_id = "a6777e7f-6a59-4019-94be-74b218365cc3" # 替换为你的 D1 数据库 ID
